name: Metrics

on:
  schedule:
    - cron: "0 0 * * *"  # Run daily at midnight
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment:
      name: production
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure full git history for activity/habits

      - name: Generate GitHub Metrics
        uses: lowlighter/metrics@latest
        continue-on-error: true  # prevent crash if one plugin fails
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Basic settings
          user: Kingsmen732
          template: classic
          base: header, community, repositories, metadata
          config_timezone: Asia/Kolkata
          config_display: large
          config_padding: 8
          config_output: public

          # Disable recent activity and coding activity (removed)
          plugin_activity: no

          # Habits
          plugin_habits: yes
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_from: 90 days ago  # shortened to avoid empty response

          # Introduction
          plugin_introduction: yes
          plugin_introduction_title: yes

          # IsoCalendar
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          # Languages
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%

          # Notable Repositories
          plugin_notable: yes
          plugin_notable_from: organization

          # Stars
          plugin_stars: yes
          plugin_stars_limit: 4

          # Traffic
          plugin_traffic: yes

      # --- Extra Metrics Modules ---

      - name: WakaTime
        uses: lowlighter/metrics@latest
        continue-on-error: true
        with:
          filename: metrics.plugin.wakatime.svg
          token: NOT_NEEDED
          base: ""
          plugin_wakatime: yes
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}

      - name: Organization Introduction
        uses: lowlighter/metrics@latest
        continue-on-error: true
        with:
          filename: metrics.plugin.introduction.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: github
          base: header
          plugin_introduction: yes

      - name: Compact Achievements
        uses: lowlighter/metrics@latest
        continue-on-error: true
        with:
          filename: metrics.plugin.achievements.compact.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_achievements: yes
          plugin_achievements_only: >-
            polyglot, stargazer, sponsor, deployer, member, maintainer, developer,
            scripter, packager, explorer, infographile, manager
          plugin_achievements_display: compact
          plugin_achievements_threshold: X

      - name: With Worldmap
        uses: lowlighter/metrics@latest
        continue-on-error: true
        with:
          filename: metrics.plugin.stargazers.worldmap.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_stargazers: yes
          plugin_stargazers_charts: no
          plugin_stargazers_worldmap: yes
          plugin_stargazers_worldmap_token: ${{ secrets.GOOGLE_MAP_TOKEN }}
          plugin_stargazers_worldmap_sample: 200

      - name: Labels
        uses: lowlighter/metrics@latest
        continue-on-error: true
        with:
          filename: metrics.plugin.topics.svg
          token: NOT_NEEDED
          base: ""
          plugin_topics: yes
          plugin_topics_limit: 12

      - name: Icons
        uses: lowlighter/metrics@latest
        continue-on-error: true
        with:
          filename: metrics.plugin.topics.icons.svg
          token: NOT_NEEDED
          base: ""
          plugin_topics: yes
          plugin_topics_limit: 0
          plugin_topics_mode: icons

      - name: Download Lysia ASCII GIF
        run: |
          mkdir -p assets
          curl -L "https://media.tenor.com/g58NwNDNNkQAAAAC/lysia-lysia-ascii.gif" -o assets/lysia_ascii.gif

      - name: Commit and Push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git pull origin main
          git add .
          git commit -m "🔄 Updated metrics and assets" || echo "No changes to commit"
          git push origin main
