name: Metrics

on:
  schedule:
    - cron: "0 0 * * *"  # Run daily at midnight
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment:
      name: production
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensure full git history for activity/habits

      - name: Generate GitHub Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Basic settings
          user: Kingsmen732
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Kolkata  # Chennai/India timezone

          # Achievements
          plugin_achievements: no
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C

          # Activity
          plugin_activity: yes
          plugin_activity_days: 14
          plugin_activity_filter: push, issue, pr, release, review, comment
          plugin_activity_limit: 5
          plugin_activity_load: 300
          plugin_activity_visibility: all

          # Habits
          plugin_habits: yes
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_from: 200 days ago

          # Introduction
          plugin_introduction: yes
          plugin_introduction_title: yes

          # IsoCalendar
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          # Languages
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%

          # Notable Repositories
          plugin_notable: yes
          plugin_notable_from: organization

          # Stars
          plugin_stars: yes
          plugin_stars_limit: 4

          # Traffic
          plugin_traffic: yes

          # 🌍 Stargazers World Map
          plugin_stargazers: yes
          plugin_stargazers_charts: no
          plugin_stargazers_worldmap: yes
          plugin_stargazers_worldmap_token: ${{ secrets.GOOGLE_MAP_TOKEN }}
          plugin_stargazers_worldmap_sample: 200

          # 🏷️ Labels (Topics)
          plugin_topics: yes
          plugin_topics_limit: 12

          # 🧩 Icons (Topics in Icon Mode)
          plugin_topics_mode: icons
